### ISSUE TITLE
Routing Buttons on the home page

### ISSUE THREAD

**Issue by emilyywangg** [TechPlus-UW/Portal-FE#107]
Currently the upcoming events and mailing list buttons don't seem to go anywhere on the page. 
Let's have them link to the respective sections on the home page!
![image](https://user-images.githubusercontent.com/51860039/108612638-7f309880-73b8-11eb-9f4c-601cecde12c0.png)

**Comment by jack-lin-jql** [comment]
When I click on the upcoming event, it jumps to this position: 
![image](https://user-images.githubusercontent.com/13803465/108872221-f1c39300-75c7-11eb-85de-ed0875f16946.png)
This is because the top navBar is not taken into account when going to the hrefed section. Can we try to find a way to compensate for the navBar so after clicking upcoming event, we show this: 
![image](https://user-images.githubusercontent.com/13803465/108872351-14ee4280-75c8-11eb-8fef-108ba976dda4.png)
